[package]
name = "pages"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
chrono-tz = "0.8.3"
dotenv = "0.15.0"
reqwest = { version = "0.11.20", features = ["blocking", "json"] }
serde = { version="1.0.188", features = ["derive"]}
serde_json = "1.0.107"
